### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by sigur123** [MJRLegends/Space-Astronomy-Feedback-#173]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27.12.15 18:52
Description: Initializing game

java.lang.RuntimeException: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
 at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:199)
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:193)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: org.lwjgl.LWJGLException: Could not create context (WGL_ARB_create_context)
 at org.lwjgl.opengl.WindowsContextImplementation.nCreate(Native Method)
 at org.lwjgl.opengl.WindowsContextImplementation.create(WindowsContextImplementation.java:50)
 at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
 at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:77)
 at org.lwjgl.opengl.DrawableGL.createSharedContext(DrawableGL.java:41)
 at org.lwjgl.opengl.SharedDrawable.<init>(SharedDrawable.java:50)
 at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:192)
 ... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
 at cpw.mods.fml.client.SplashProgress.start(SplashProgress.java:199)
 at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:193)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
 at net.minecraft.client.main.Main.main(SourceFile:148)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Windows 7 (amd64) version 6.1
 Java Version: 1.7.0_79, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 398548848 bytes (380 MB) / 771751936 bytes (736 MB) up to 3817865216 bytes (3641 MB)
 JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: 
 GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1.8545 Release' Renderer: 'Radeon X1600 Series (Microsoft Corporation - WDDM)    '
 Launched Version: forge-10.13.4.1517
 LWJGL: 2.9.1
 OpenGL: Radeon X1600 Series (Microsoft Corporation - WDDM)     GL version 2.1.8545 Release, ATI Technologies Inc.
 GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: []
 Current Language: ERROR NullPointerException: null
 Profiler Position: N/A (disabled)
 Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 Anisotropic Filtering: Off (1)

**Comment by MJRLegends** [comment]
Try reinstalling the mod pack

**Comment by sigur123** [comment]
I have the same issue after reinstalling the modpack. I tried curse and ftb. Can you please help me somehow?

**Comment by MJRLegends** [comment]
Does any of the other mod packs work

**Comment by sigur123** [comment]
Yes, for example Agrarian skies 2 works.

**Comment by MJRLegends** [comment]
ummm, have you added anything to the mod pack like optifine?

**Comment by sigur123** [comment]
No, I haven't. I am trying to play it for the first time.

**Comment by MJRLegends** [comment]
Ok can you try and load FTB Infinity and see if it works

**Comment by sigur123** [comment]
Doesn't work. I think it is the same crash report. http://pastebin.com/YxiTfZSq

**Comment by MJRLegends** [comment]
Yeah thats what i thought it would do and i think its a problem with your hardware/drivers being out of date and having issues with Java/LWJGL(OpenGL), you could try updating your graphics card drivers or/and Java. Or you could go to the Config folder for the mod packs that dont wont and go to the "splash.properties" file then change the "enabled=true" to "enabled=false"

**Comment by sigur123** [comment]
Thank you, changing it in the splash.properties works.

**Comment by MJRLegends** [comment]
No problem :D
