### ISSUE TITLE
i was doing some advanced genetics and got DQ now i cant get back in

### ISSUE THREAD

**Issue by Ihavetherights** [MJRLegends/Space-Astronomy-Feedback-#270]
ive re downloaded the pack ive tried to direct connect and nothing works help plz

**Comment by MJRLegends** [comment]
Single player or multiplayer? If multiplayer which server?

**Comment by Ihavetherights** [comment]
multiplayer space.mjrlegends.com

**Comment by MJRLegends** [comment]
Can you send me your log after trying to connect

**Comment by Ihavetherights** [comment]
[2016-04-17-2.log.gz](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/223577/2016-04-17-2.log.gz)

[2016-04-17-1.log.gz](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/223579/2016-04-17-1.log.gz)

**Comment by Ihavetherights** [comment]
i just tried again and it wont let me post this one so im just gona copy and paste it

**Comment by Ihavetherights** [comment]
[12:47:33] [main/INFO]: Setting user: Ihavetherights
[12:47:36] [Client thread/INFO]: LWJGL Version: 2.9.1
[12:48:14] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:Advanced Genetics, FMLFileResourcePack:Advanced Solar Panels, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:Aroma1997Core|Helper, FMLFileResourcePack:Aroma1997's Dimensional World, FMLFileResourcePack:asielib, FMLFileResourcePack:BD Lib, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:Chisel Facades, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Machines, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Computronics, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Dimensional Anchors, FMLFileResourcePack:DragonAPI, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:EnhancedPortals, FMLFileResourcePack:Extra Cells 2, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Graviation Suite, FMLFileResourcePack:Hats, FMLFileResourcePack:Hardcore Questing Mode, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:In-Game wiki Mod, FMLFileResourcePack:Immersive Engineering, FMLFileResourcePack:Immersive Integration, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:Integrated Circuits, FMLFileResourcePack:AppliedAerodynamics, FMLFileResourcePack:AppliedAerodynamicsNEI, FMLFileResourcePack:IntelliE, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Logistics Pipes, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:Mimicry, FMLFileResourcePack:Minechem, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:More Planets, FMLFileResourcePack:MorePlanetsExtras, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:NEI Addons: Developer Tools, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:Numina, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:OpenMods, FMLFileResourcePack:Open Modular Turrets, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:OpenSecurity, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:Practicalities, FMLFileResourcePack:ProjectRed Core, FMLFileResourcePack:ProjectRed Compatibility, FMLFileResourcePack:ProjectRed Fabrication, FMLFileResourcePack:ProjectRed Integration, FMLFileResourcePack:ProjectRed Transmission, FMLFileResourcePack:ProjectRed Illumination, FMLFileResourcePack:ProjectRed Expansion, FMLFileResourcePack:ProjectRed Transportation, FMLFileResourcePack:ProjectRed Exploration, FMLFileResourcePack:QuarryPlus, FMLFileResourcePack:Railcraft, FMLFileResourcePack:Random Things, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slimevoid Library, FMLFileResourcePack:SpaceAstronomyTweaks, FMLFileResourcePack:Soul Shards Reborn, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Storage Drawers: Biomes O' Plenty Pack, FMLFileResourcePack:Storage Drawers: Misc Pack, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Wireless Redstone, FMLFileResourcePack:YAMPST, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MCFrames, FMLFileResourcePack:ForgeRelocation, FMLFileResourcePack:RelocationFMP, FMLFileResourcePack:MrTJPCore
[12:48:15] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:48:15] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:48:15] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:48:59] [Sound Library Loader/INFO]: Sound engine started
[12:49:46] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:Advanced Genetics, FMLFileResourcePack:Advanced Solar Panels, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:Aroma1997Core|Helper, FMLFileResourcePack:Aroma1997's Dimensional World, FMLFileResourcePack:asielib, FMLFileResourcePack:BD Lib, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:Chisel Facades, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Machines, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Computronics, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Dimensional Anchors, FMLFileResourcePack:DragonAPI, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:EnhancedPortals, FMLFileResourcePack:Extra Cells 2, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Graviation Suite, FMLFileResourcePack:Hats, FMLFileResourcePack:Hardcore Questing Mode, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:In-Game wiki Mod, FMLFileResourcePack:Immersive Engineering, FMLFileResourcePack:Immersive Integration, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:Integrated Circuits, FMLFileResourcePack:AppliedAerodynamics, FMLFileResourcePack:AppliedAerodynamicsNEI, FMLFileResourcePack:IntelliE, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Logistics Pipes, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:Mimicry, FMLFileResourcePack:Minechem, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:More Planets, FMLFileResourcePack:MorePlanetsExtras, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:NEI Addons: Developer Tools, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:Numina, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:OpenMods, FMLFileResourcePack:Open Modular Turrets, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:OpenSecurity, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:Practicalities, FMLFileResourcePack:ProjectRed Core, FMLFileResourcePack:ProjectRed Compatibility, FMLFileResourcePack:ProjectRed Fabrication, FMLFileResourcePack:ProjectRed Integration, FMLFileResourcePack:ProjectRed Transmission, FMLFileResourcePack:ProjectRed Illumination, FMLFileResourcePack:ProjectRed Expansion, FMLFileResourcePack:ProjectRed Transportation, FMLFileResourcePack:ProjectRed Exploration, FMLFileResourcePack:QuarryPlus, FMLFileResourcePack:Railcraft, FMLFileResourcePack:Random Things, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slimevoid Library, FMLFileResourcePack:SpaceAstronomyTweaks, FMLFileResourcePack:Soul Shards Reborn, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Storage Drawers: Biomes O' Plenty Pack, FMLFileResourcePack:Storage Drawers: Misc Pack, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Wireless Redstone, FMLFileResourcePack:YAMPST, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MCFrames, FMLFileResourcePack:ForgeRelocation, FMLFileResourcePack:RelocationFMP, FMLFileResourcePack:MrTJPCore, FMLFileResourcePack:Carpenter's Blocks Cached Resources, XU_Delegate_Pack, XU_Delegate_Pack, XU_Delegate_Pack, opensecurity_external
[12:49:46] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:49:46] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:49:46] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:50:02] [Sound Library Loader/INFO]: Sound engine started
[12:50:04] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:ArmorStatusHUD, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:Advanced Genetics, FMLFileResourcePack:Advanced Solar Panels, FMLFileResourcePack:AE2 Stuff, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:Aroma1997Core|Helper, FMLFileResourcePack:Aroma1997's Dimensional World, FMLFileResourcePack:asielib, FMLFileResourcePack:BD Lib, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BC Robotics, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Factory, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:Chisel Facades, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Machines, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Computronics, FMLFileResourcePack:Custom Main Menu, FMLFileResourcePack:Dimensional Anchors, FMLFileResourcePack:DragonAPI, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:EnhancedPortals, FMLFileResourcePack:Extra Cells 2, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Graviation Suite, FMLFileResourcePack:Hats, FMLFileResourcePack:Hardcore Questing Mode, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:In-Game wiki Mod, FMLFileResourcePack:Immersive Engineering, FMLFileResourcePack:Immersive Integration, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:InGame Info XML, FMLFileResourcePack:Integrated Circuits, FMLFileResourcePack:AppliedAerodynamics, FMLFileResourcePack:AppliedAerodynamicsNEI, FMLFileResourcePack:IntelliE, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Logistics Pipes, FMLFileResourcePack:LunatriusCore, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:Mimicry, FMLFileResourcePack:Minechem, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:MineTweaker 3, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:More Planets, FMLFileResourcePack:MorePlanetsExtras, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:NEI Addons: Developer Tools, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:Numina, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenComputers, FMLFileResourcePack:OpenMods, FMLFileResourcePack:Open Modular Turrets, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:OpenSecurity, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:Practicalities, FMLFileResourcePack:ProjectRed Core, FMLFileResourcePack:ProjectRed Compatibility, FMLFileResourcePack:ProjectRed Fabrication, FMLFileResourcePack:ProjectRed Integration, FMLFileResourcePack:ProjectRed Transmission, FMLFileResourcePack:ProjectRed Illumination, FMLFileResourcePack:ProjectRed Expansion, FMLFileResourcePack:ProjectRed Transportation, FMLFileResourcePack:ProjectRed Exploration, FMLFileResourcePack:QuarryPlus, FMLFileResourcePack:Railcraft, FMLFileResourcePack:Random Things, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Slimevoid Library, FMLFileResourcePack:SpaceAstronomyTweaks, FMLFileResourcePack:Soul Shards Reborn, FMLFileResourcePack:Storage Drawers, FMLFileResourcePack:Storage Drawers: Biomes O' Plenty Pack, FMLFileResourcePack:Storage Drawers: Misc Pack, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Vein Miner, FMLFileResourcePack:Mod Support, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:Wireless Redstone, FMLFileResourcePack:YAMPST, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:MCFrames, FMLFileResourcePack:ForgeRelocation, FMLFileResourcePack:RelocationFMP, FMLFileResourcePack:MrTJPCore, FMLFileResourcePack:Carpenter's Blocks Cached Resources, XU_Delegate_Pack, XU_Delegate_Pack, XU_Delegate_Pack, opensecurity_external
[12:50:04] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:50:04] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:50:04] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: moreplanetsExtras in C:\Users\bradley\Documents\Curse\Minecraft\Instances\Space Astronomy\mods\MorePlanetsExtras-1.0.jar
[12:50:14] [Sound Library Loader/INFO]: Sound engine started
[12:53:09] [Client thread/INFO]: Connecting to space-mc.mjrlegends.com., 25588
[12:53:13] [pool-2-thread-1/INFO]: [CHAT] New Logistics Pipes build found: #114
[12:53:13] [pool-2-thread-1/INFO]: [CHAT] Use "/logisticspipes changelog" to see a changelog.
[12:53:22] [Client thread/INFO]: [CHAT] §eDragonAPI Notification:
[12:53:22] [Client thread/INFO]: [CHAT] §dDragonAPI§r is out of date, likely has errors, and is no longer supported. Update to v12e.
[12:53:22] [Client thread/INFO]: [CHAT] §eTo disable this notifcation for any mod, type "/checker disable [modname]".
[12:53:22] [Client thread/INFO]: [CHAT] §eChanges take effect upon server or client restart.
[12:53:27] [Client thread/INFO]: [CHAT] This server doesn't have Hardcore Questing Mode enabled.
[12:53:27] [Client thread/INFO]: [CHAT] Ihavetherights joined the game.
[12:53:27] [Client thread/INFO]: [CHAT] You have no new mail.
[12:53:27] [Client thread/INFO]: [CHAT] denirodi left the game.
[12:53:27] [Client thread/INFO]: [CHAT] null
[12:53:33] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.world.World.func_72939_s(World.java:1954) ~[ahb.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.advGenetics.TileEntity.TileEntityDNACombiner.func_145845_h(TileEntityDNACombiner.java:157) ~[TileEntityDNACombiner.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	... 10 more

**Comment by MJRLegends** [comment]
Your DNA combiner was crashing the server and i've had to remove the block from the world, try now

**Comment by Ihavetherights** [comment]
im at school now ill try when i get home oh and btw i lost my fly and no fall gene in the process of crashing... i mean i have another but i would have to re complete them. i dont know what would happen if i tryed to re make them, would it crash again. it would be nice if you could just give me the syringe for it cause i really dont wanna crash again. if not its fine if i crash ill just contact you again. thank you
