### ISSUE TITLE
Late versions won't load

### ISSUE THREAD

**Issue by Chinthor** [MJRLegends/Space-Astronomy-Feedback-#271]
I have this error with latest and a few recent versions of Space Astronomy and Evolving Technology. Even after modpack delete and clean install. *Note* I got SA to launch after installing the very first version. Don't know how new I can get and still work. Any ideas?

[18:00:12] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:00:12] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by Chinthor** [comment]
After a lot of testing, I can open most versions under 2.0.0 and the 2.0.3 and 2.0.4 alpha versions. Nothing else will load beyond this error.

**Comment by MJRLegends** [comment]
The latest version of Space Astronomy is 1.4.3 so please use that version
