### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Chinthor** [MJRLegends/Space-Astronomy-Feedback-#287]
I've been trying to make this work, starting from Curse files. I now understand that FTB has a server pack, so I'll be trying that. In the mean time, consider this a bit of an FYI.

After eliminating everything that is client side only and causes issues, I still get this error. Process of elimination led me to add in the mods a few at a time. The error only shows when I leave Intelligent Energistics on the server. Delete it and errors go away. Spent a lot of time chasing down things that didn't fix it. Removing open peripherals or railcrat or various mekanism modules only gave me new and different errors, most beginning with the Exception in server tick loop. Again, adding/removing things one at a time pointed to Intelligent Energistics, and I have no earthly idea why.

---- Minecraft Crash Report ----
// Don't do that.

Time: 5/7/16 1:16 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.ClassNotFoundException: mekanism.generators.common.GeneratorsItems
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:76)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: mekanism.generators.common.GeneratorsItems

**Comment by MJRLegends** [comment]
One use pastebin.com for logs does say here https://github.com/MJRLegends/Space-Astronomy-Feedback-/blob/master/CONTRIBUTING.md and use the server files provided on the ftb launcher and then try this again
