### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VanedS** [MJRLegends/Space-Astronomy-Feedback-#329]
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.net.ConnectException: Connection refused: connect
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.PlainSocketImpl.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.SocksSocketImpl.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.Socket.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.Socket.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.NetworkClient.doConnect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.http.HttpClient.openServer(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.http.HttpClient.<init>(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.http.HttpClient.New(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.http.HttpClient.New(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.access$100(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.voxio.yampst.common.StatsManager.post(StatsManager.java:370)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.voxio.yampst.common.StatsManager.post(StatsManager.java:315)
[13:47:19] [Thread-12/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.voxio.yampst.common.StatsManager$ShutdownThread.run(StatsManager.java:103)

**Comment by MJRLegends** [comment]
You cleary didn't read this https://github.com/MJRLegends/Space-Astronomy-Feedback-/blob/master/CONTRIBUTING.md

**Comment by VanedS** [comment]
2?

**Comment by WalaoEgg0424** [comment]
@VanedS paste the log at pastebin then give the link , and tell us what issue is it , not just the error.

**Comment by VanedS** [comment]
![image](https://cloud.githubusercontent.com/assets/20012567/16170500/2ca39e8a-355d-11e6-95ef-eb83972cbf31.png)

**Comment by MJRLegends** [comment]
Stop removing mods and that won't happen lol

**Comment by MJRLegends** [comment]
Please repost your issue when you have the proper information to give to me
