### ISSUE TITLE
Using Tinkers LumberAxe crashes client

### ISSUE THREAD

**Issue by NavroDK** [MJRLegends/Space-Astronomy-Feedback-#357]
If you use the Tinkers LumberAxe the client crashes as soon as the "Chopping" is done, and the tree is disappearing.

Stacktrace from Client crash
`Stacktrace:
	at portablejim.veinminer.core.CoreEvents.blockBreakEvent(CoreEvents.java:25)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_624_CoreEvents_blockBreakEvent_BreakEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at tconstruct.items.tools.LumberAxe.breakTree(LumberAxe.java:173)
	at tconstruct.items.tools.LumberAxe.onBlockStartBreak(LumberAxe.java:101)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78751_a(PlayerControllerMP.java:96)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78759_c(PlayerControllerMP.java:247)
	at net.minecraft.client.Minecraft.func_147115_a(Minecraft.java:1357)` 

Full crash report attached
[crash-2016-06-29_16.52.59-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/339634/crash-2016-06-29_16.52.59-client.txt)

**Comment by Markus9063** [comment]
same happened to me, then my pc crashed lol, had to manualy restart me pc

**Comment by MJRLegends** [comment]
Simple temp fix dont use them tools and vein miner

**Comment by Markus9063** [comment]
why not just go back to 1.4.5, almost all the servers are on that version

**Comment by MJRLegends** [comment]
Well firstly why dont you stop being so rude

**Comment by NavroDK** [comment]
Disabled Veinminer mod, and as you wrote it fixed the crash - Thanks :+1:

**Comment by MJRLegends** [comment]
No problem i will get another update out soon clearly the new version is vein miner is broken
