### ISSUE TITLE
Game crashes out of nowhere

### ISSUE THREAD

**Issue by Klade97** [MJRLegends/Space-Astronomy-Feedback-#373]
[00:09:16] [Client thread/ERROR] [NotEnoughItems]: Error loading recipe: 
java.lang.ArrayIndexOutOfBoundsException is the error code i got, idk if it is what caused the crash or if it is this line of code:

[00:09:16] [Client thread/WARN] [IC2.Item]: Detected invalid armor damage application:
java.lang.Throwable
	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
	at net.minecraft.item.ItemStack.func_77964_b(ItemStack.java:222) [add.class:?]
	at codechicken.nei.PositionedStack.setPermutationToRender(PositionedStack.java:99) [PositionedStack.class:?]
	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:34) [PositionedStack.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.setIngredients(ShapedRecipeHandler.java:53) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.forgeShapedRecipe(ShapedRecipeHandler.java:160) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.loadUsageRecipes(ShapedRecipeHandler.java:137) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:350) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:472) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) [RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) [bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Klade97** [comment]
It runs fine for me through the Curse speak launcher but not through ftb launcher and normally it runs for 2-3 hours and then crashes

**Comment by MJRLegends** [comment]
Post the log in a pastebin not here!!!

**Comment by Klade97** [comment]
im new to this site so idk what or where the pastebin is...

**Comment by MJRLegends** [comment]
Www.Pastebin.com

**Comment by Klade97** [comment]
thanks

**Comment by MJRLegends** [comment]
Also i need the full crash log

**Comment by Klade97** [comment]
ok how do you want me to put it in pastebin?

**Comment by Klade97** [comment]
ok weird it didnt create a crash log of 12:14 when it happened

**Comment by Klade97** [comment]
[crash-2016-07-01_17.21.46-client.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/344447/crash-2016-07-01_17.21.46-client.txt)

**Comment by MJRLegends** [comment]
Update your mod pack

**Comment by Klade97** [comment]
its 1.4.7
