### ISSUE TITLE
Client crashs by showing NEI recepies

### ISSUE THREAD

**Issue by Panakotta00** [MJRLegends/Space-Astronomy-Feedback-#387]
Hey Guys,
my problem is, on my server, when I show an recepie of an Item/Block in NEI my client crashs and at the Server I have an Error (not an Crash), the Error is:

```
[13:52:57] [Netty IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_91]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_91]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_91]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_91]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_91]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

but in Singleplayer I can show recepies.

Can anybody help me?

**Comment by MJRLegends** [comment]
Weird, does it happen on any other server

**Comment by Panakotta00** [comment]
I don't test it on other servers, but why did it work earlyer perfect?

**Comment by MJRLegends** [comment]
idk i think you was just having internet/network issues with mc
