### ISSUE TITLE
Space Astronomy Bug

### ISSUE THREAD

**Issue by tilly1709** [MJRLegends/Space-Astronomy-Feedback-#40]
My Space Astronomy won't launch. I click launch and it looks as thought it's going to load and then it just bugs out and stops. I've not been able to get on the server and so I've never been on it. If it does ever work, it'd be my first time.

**Comment by MJRLegends** [comment]
i would need the logs/crash log

**Comment by tilly1709** [comment]
If it's the code that comes up in the separate window, it doesn't get far enough to have any.

**Comment by tilly1709** [comment]
[18:54:59] [DEBUG] Main.main:170: Launcher arguments: []
[18:54:59] [DEBUG] Main.main:171: Launcher PID: 9072
[18:54:59] [DEBUG] Main.main:182: FTB Launcher CI Build #: 344, Git SHA: b7f7123d76dc
[18:54:59] [INFO] MainHelpers.printInfo:39: FTBLaunch starting up (version 1.4.8 Build: 10408)
[18:54:59] [DEBUG] MainHelpers.printInfo:40: System's default JVM: (This is not always used to launch MC)
[18:54:59] [DEBUG] MainHelpers.printInfo:41: Java version: 1.7.0_79
[18:54:59] [DEBUG] MainHelpers.printInfo:42: Java vendor: Oracle Corporation
[18:54:59] [DEBUG] MainHelpers.printInfo:43: Java home: C:\Program Files\Java\jre7
[18:54:59] [DEBUG] MainHelpers.printInfo:44: Java specification: Java Virtual Machine Specification version: 1.7 by Oracle Corporation
[18:54:59] [DEBUG] MainHelpers.printInfo:46: Java vm: Java HotSpot(TM) 64-Bit Server VM version: 24.79-b02 by Oracle Corporation
[18:54:59] [INFO] MainHelpers.printInfo:47: OS: Windows 8.1 6.3 (64-bit)
[18:54:59] [INFO] MainHelpers.printInfo:48: Launcher Install Dir: c:\ftb
[18:54:59] [INFO] JGoogleAnalyticsTracker$2.run:484: AnalyticsBackgroundThread started
[18:54:59] [INFO] MainHelpers.printInfo:49: System memory: 4560M free, 7098M total
[18:55:00] [ERROR] OutputOverride.write:45: From Console: Sep 28, 2015 6:55:00 PM java.util.prefs.WindowsPreferences &lt;init&gt;
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[18:55:02] [INFO] JavaFinder.parseJavaVersion:175: The FTB Launcher has found the following Java versions installed:
[18:55:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.8.0_51 sorted as: 1.8.0_51 32 Bit Java at : C:\Program Files (x86)\Java\jre1.8.0_51\bin\java.exe
[18:55:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.7.0_79 sorted as: 1.7.0_79 64 Bit Java at : C:\Program Files\Java\jre7\bin\java.exe
[18:55:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.7.0_79 sorted as: 1.7.0_79 64 Bit Java at : C:\WINDOWS\system32\java.exe
[18:55:02] [INFO] JavaFinder.parseJavaVersion:177: Java Version: 1.7.0_79 sorted as: 1.7.0_79 64 Bit Java at : C:\Program Files\Java\jre7\bin\java.exe
[18:55:02] [INFO] JavaFinder.parseJavaVersion:204: Preferred: Java Version: 1.7.0_79 sorted as: 1.7.0_79 64 Bit Java at : C:\Program Files\Java\jre7\bin\java.exe
[18:55:02] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for http://ftb.cursecdn.com
[18:55:02] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for http://www.creeperrepo.net
[18:55:02] [DEBUG] DownloadUtils.run:450: DownloadUtils.run() starting
[18:55:02] [INFO] I18N.addFiles:97: [i18n] Fallback enUS loaded
[18:55:02] [INFO] I18N.setLocale:120: [i18n] enGB English (GB) language file loaded!
[18:55:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Balance (curse) took 371 ms.
[18:55:02] [INFO] LoadingDialog.advance:46: Checking installation location
[18:55:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Balance took 430 ms.
[18:55:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Curse edges.json took 567 ms.
[18:55:02] [DEBUG] DownloadUtils.run:546: DL ready
[18:55:02] [INFO] DownloadUtils.run:579: Using download server Automatic:CurseCDN on host ftb.cursecdn.com (198.41.209.103)
[18:55:02] [DEBUG] Benchmark.logBenchAs:73: Download Utils Init took 567 ms.
[18:55:03] [INFO] LoadingDialog.advance:46: Loading user data
[18:55:04] [DEBUG] OSUtils.getMacAddress:412: Interface: Microsoft Hosted Network Virtual Adapter : wlan0
[18:55:04] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/hatfilms.xml took 666 ms.
[18:55:04] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:103: Loading modpack information for hatfilms.xml...
[18:55:04] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/spacea.xml took 713 ms.
[18:55:04] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:103: Loading modpack information for spacea.xml...
[18:55:05] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/modpacks.xml took 1133 ms.
[18:55:05] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:103: Loading modpack information for modpacks.xml...
[18:55:05] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/devco.xml took 1321 ms.
[18:55:05] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:103: Loading modpack information for devco.xml...
[18:55:06] [DEBUG] Benchmark.logBenchAs:73: Modpack Loader http://ftb/thirdparty.xml took 2321 ms.
[18:55:06] [INFO] ModpackLoader$XmlHtmlRunnable.handleXML:103: Loading modpack information for thirdparty.xml...
[18:55:06] [INFO] LoadingDialog.advance:46: Creating Console window
[18:55:06] [INFO] MainHelpers.googleAnalytics:158: Reporting daily use
[18:55:06] [INFO] LoadingDialog.advance:46: Creating main window
[18:55:06] [DEBUG] AuthlibDLWorker.doInBackground:57: Loading Authlib...
[18:55:08] [INFO] AuthlibDLWorker.downloadJars:136: Local Authlib Version is good, skipping Download
[18:55:08] [INFO] AuthlibDLWorker.doInBackground:69: Adding Authlib to Classpath
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 0 enUS to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 1 cyGB to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 2 daDK to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 3 deDE to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 4 enGB to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 5 enUS to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 6 esES to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 7 fiFI to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 8 frCA to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 9 frFR to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 10 itIT to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 11 maHU to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 12 nlNL to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 13 noNO to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 14 plPL to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 15 ptBR to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 17 ruRU to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 16 ptPT to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 19 zhCN to options pane
[18:55:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 18 svSE to options pane
[18:55:09] [INFO] I18N.setLocale:120: [i18n] enGB English (GB) language file loaded!
[18:55:09] [DEBUG] Benchmark.logBenchAs:73: UnreadNews Init took 43 ms.
[18:55:09] [DEBUG] Benchmark.logBench:59: NewsUtils took 1025 ms.
[18:55:10] [INFO] LoadingDialog.advance:46: Setting up Launcher
[18:55:10] [DEBUG] UpdateChecker.&lt;init&gt;:71: Launcher Install path: C:\Users\Connie-Louise\Downloads\FTB_Launcher.exe
[18:55:10] [INFO] LoadingDialog.advance:46: Downloading pack data
[18:55:11] [DEBUG] Benchmark.logBenchAs:73: Authlib DL Worker Init took 4431 ms.
[18:55:13] [DEBUG] UpdateChecker.shouldUpdate:132: updater: buildjenk 344 &lt; betajenk 341|| version 10408 &lt; 10408
[18:55:13] [DEBUG] UpdateChecker.shouldUpdate:133: latest = 10408
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: All modpack lists loaded took 11255 ms.
[18:55:15] [DEBUG] Benchmark.logBench:59: Waiting for main window took 0 ms.
[18:55:15] [INFO] LoadingDialog.advance:46: Opening main window
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(Modpacks loaded) took 15506 ms.
[18:55:15] [DEBUG] LaunchFrame$14.run:451: Last used packs: Magic_World_2 TPPI
[18:55:15] [INFO] MapLoader.run:43: loading map information...
[18:55:15] [INFO] TexturePackLoader.run:43: loading texture pack information...
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: MapLoader run  took 541 ms.
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(maps or texturepacks loaded) took 16048 ms.
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: Texture Pack Load  took 599 ms.
[18:55:15] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(maps and texturepacks loaded) took 16105 ms.
[18:55:16] [DEBUG] Benchmark.logBenchAs:73: Launcher Startup(main window opened and ready to use) took 17115 ms.
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 1 (FTB Trident Default Map)
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 2 (Agrarian Skies Default Map)
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 3 (Agrarian Skies Flat Map)
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 4 (Agrarian Skies Server Map)
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 5 (Direwolf20 Map Ep.0)
[18:55:16] [INFO] MapUtils$6.run:250: Adding map 6 (FTB Pax Challenge)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 7 (Direwolf20 Map Ep.0)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 8 (Direwolf20 Map Ep.10)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 9 (Direwolf20 Map Ep.20)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 10 (Direwolf20 Map Ep.30)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 11 (Direwolf20 Map Ep.40)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 12 (Direwolf20 Map Ep.50)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 13 (Direwolf20 Map Ep.80)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 14 (FTB Normal)
[18:55:17] [INFO] MapUtils$6.run:250: Adding map 15 (FTB Insanity)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 1 (Soartex Fanver)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 2 (Jadedcat Mixpack)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 3 (Invictus)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 4 (Faithful)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 5 (JohnSmith Technicians Remix)
[18:55:17] [INFO] TexturepackPane$6.run:237: Adding texture pack 6 (Familiar yet Different)
[18:55:50] [INFO] LaunchFrame.doLogin:536: Logging in...
[18:55:50] [DEBUG] OSUtils.getProxy:77: ProxySelector: type: DIRECT, no proxy for https://authserver.mojang.com/authenticate
[18:55:50] [DEBUG] AuthlibHelper.authenticateWithAuthlib:67: Username given Not 100% sure, mojangdata might contain different username
[18:55:50] [INFO] AuthlibHelper.authenticateWithAuthlib:68: Beginning authlib authentication attempt
[18:55:50] [INFO] AuthlibHelper.authenticateWithAuthlib:69: successfully created YggdrasilAuthenticationService
[18:55:50] [DEBUG] AuthlibHelper.authenticateWithAuthlib:76: mojangData was passed to current method
[18:55:50] [DEBUG] AuthlibHelper.authenticateWithAuthlib:79: Loading mojangData into authlib
[18:55:52] [DEBUG] AuthlibHelper.authenticateWithAuthlib:148: Authentication is valid 
[18:55:52] [DEBUG] AuthlibHelper.authenticateWithAuthlib:151: loggedIn() &amp;&amp; CanPlayOnline()
[18:55:52] [DEBUG] AuthlibHelper.authenticateWithAuthlib:155: Authentication done, returning LoginResponse
[18:55:52] [DEBUG] Benchmark.logBenchAs:73: Login Worker Run took 1718 ms.
[18:55:52] [DEBUG] LaunchFrame$16.done:580: responseStr: good
[18:55:52] [INFO] LaunchFrame$16.done:583: Login complete.
[18:55:52] [DEBUG] User.writeObject:185: starting...
[18:55:52] [DEBUG] LaunchFrame$16.done:587: user data saved
[18:55:52] [DEBUG] LaunchFrame.runGameUpdater:634: ForceUpdate: false
[18:55:52] [DEBUG] LaunchFrame.runGameUpdater:635: installPath: c:\ftb
[18:55:52] [DEBUG] LaunchFrame.runGameUpdater:636: pack dir: SpaceAstronomy
[18:55:52] [DEBUG] LaunchFrame.runGameUpdater:637: pack check path: SpaceAstronomy\version
[18:55:52] [DEBUG] LaunchFrame.checkVersion:612: verFile: 1.2.6 onlineVersion/getPackVer(): Recommended Version onlineVersion/getVersion(): 1.2.6
[18:55:52] [INFO] MCInstaller.gatherAssets:127: Checking local assets file, for MC version1.7.10 Please wait! 
[18:55:52] [DEBUG] MCInstaller.gatherAssets:132: Checking pack libraries
[18:55:52] [DEBUG] MCInstaller.gatherAssets:184: Checking minecraft version json
[18:55:53] [DEBUG] MCInstaller.gatherAssets:199: checking minecraft libraries
[18:55:53] [DEBUG] MCInstaller.gatherAssets:267: Checking minecraft assets
[18:55:54] [DEBUG] MCInstaller.gatherAssets:281: Starting TaskHandler to check MC assets
[18:56:03] [DEBUG] Benchmark.logBenchAs:73: parallel asset check took 8748 ms.
[18:56:03] [INFO] MCInstaller.launchMinecraft:328: Setting up native libraries for Space Astronomy v Recommended Version MC 1.7.10
[18:56:03] [DEBUG] MCInstaller.launchMinecraft:354: packbaseJSON 1.7.10
[18:56:05] [INFO] MCLauncher.syncAssets:286: Syncing Assets:
[18:56:05] [INFO] MCLauncher.launchMinecraft:86: Java Path: C:\Program Files\Java\jre7\bin\javaw.exe
[18:56:05] [INFO] MCLauncher.launchMinecraft:87: Pack: Space Astronomy 1.7.10
[18:56:05] [INFO] MCLauncher.setMemory:269: Setting MinMemory to 256
[18:56:05] [INFO] MCLauncher.setMemory:271: Setting MaxMemory to 2048
[18:56:05] [INFO] MCLauncher.launchMinecraft:110: Defaulting PermSize to 256m
[18:56:05] [DEBUG] MCInstaller.launchMinecraft:428: MC PID: 1136
[18:56:07] [DEBUG] Benchmark.logBenchAs:73: UnreadNews Init took 11 ms.
[18:56:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[18:56:09] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_79]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_79]
	at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_79]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[18:56:09] [INFO] ProcessMonitor.run:43: MC process exited. return value: 1
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 0 enUS to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 1 cyGB to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 2 daDK to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 3 deDE to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 4 enGB to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 5 enUS to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 6 esES to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 7 fiFI to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 8 frCA to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 9 frFR to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 10 itIT to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 11 maHU to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 12 nlNL to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 13 noNO to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 14 plPL to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 15 ptBR to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 17 ruRU to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 16 ptPT to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 19 zhCN to options pane
[18:56:09] [INFO] OptionsPane.&lt;init&gt;:172: [i18n] Added 18 svSE to options pane
[18:56:09] [INFO] I18N.setLocale:120: [i18n] enGB English (GB) language file loaded!
[18:56:18] Post created

**Comment by MJRLegends** [comment]
This doesnt show any crash happened

**Comment by tilly1709** [comment]
I don't know what happens then, it just opens, starts loading, then stops and goes back to the launcher.

**Comment by green8751** [comment]
increase the amount of ram it can use, I had the same problem with other packs and that fixed it (I am assuming you use the FTB launcher)

**Comment by tilly1709** [comment]
How do I do that?

**Comment by tilly1709** [comment]
(Sorry if I'm being dumb)

**Comment by tilly1709** [comment]
(Or annoying)

**Comment by green8751** [comment]
If you are using the ftb launcher you go to settings, there will be a slide bar that is labeled ram or memory, slide that all the way to the right (there is a number below this that tells you how much you have allowed it to use, if you don't want it maxed) if it still won't finish launching then you need a new computer with more ram.  If you use curse than Google it

**Comment by MJRLegends** [comment]
@tilly1709 did you fix this after?

**Comment by green8751** [comment]
That was what fixed the issue for me, if it stops and dosent give you a crash report then it ran out of space and couldn't even finish launching, I only have had this problem with the ftb launcher because it let's you choose how much space it can use, if it is allowed to use everything available on your computer andit still can't finish launching you need to get a new computer, but I would try getting a clean install of Windows first just incase you have a virus using some ram space and reducing the ram space you can allow minecraft to use (should I use the technical terms for you?)
