### ISSUE TITLE
Cant connect to my world

### ISSUE THREAD

**Issue by Zweckformer** [MJRLegends/Space-Astronomy-Feedback-#539]
Hey,
I having an issue connecting to my single player world.
It appears out of nowhere, when i try to start my world. 

**Crash log/Log (if applicable):
http://pastebin.com/ucbktmrm

**Version of Mod Pack using:** 
SpaceAstronomy 1.5.2 (no manual changes to the integrated mods)
via Curse Client

It seems to me EnderIO / AE2 is the problem, but i dont know how to fix this.
I tried a second profile and copied my world, same issue, but starting a new
world seems to work just fine.
I already tried to load the pack without these mods, didn't work either.

I hope someone could help to fix this. Already played a lot in this world...:/

greetings

**Comment by Zweckformer** [comment]
if I knew, it was the "HQM-known" issue, i've found it in the known issues...thought it was a enderiO /Ae2 problem. thats why i opened this post.

fyi, problem fixed

**Comment by MJRLegends** [comment]
No it has nothing at all to do with enderiO /Ae2 ??? the crash log says HQM

` at hardcorequesting.network.DataReader.readData(DataReader.java:55)
    at hardcorequesting.Team.loadData(Team.java:860)
    at hardcorequesting.QuestingData.loadData(QuestingData.java:634)
    at hardcorequesting.QuestingData.<init>(QuestingData.java:519)
    at hardcorequesting.QuestingData.readAllData(QuestingData.java:503)
    at hardcorequesting.QuestingData$1.read(QuestingData.java:409)
    at hardcorequesting.network.FileHelper.loadData(FileHelper.java:107)
    at hardcorequesting.QuestingData.load(QuestingData.java:438)`

**Comment by Zweckformer** [comment]
I'll promise investigating my problem better next time. :) Nevertheless, thank you for your advises und the great work on this mod-pack!
