### ISSUE TITLE
Server set up crash

### ISSUE THREAD

**Issue by MrGetTheFakOf** [MJRLegends/Space-Astronomy-Feedback-#600]
i'm setting up my own server with this mod but i installed every thing correctly but it keeps giving me this crash:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/22/16 3:28 PM
Description: Exception in server tick loop

Missing Mods:
	IC2 : any

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:243)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
i hope that its allowed to ask this here.

**Comment by MJRLegends** [comment]
Missing Mods:
IC2 : any

cpw.mods.fml.common.MissingModsException

you need to redownload the server or/and client files
