### ISSUE TITLE
Can launch mod pack with FTB Launcher,But other mod pack can.

### ISSUE THREAD

**Issue by jeremywu0521** [MJRLegends/Space-Astronomy-Feedback-#773]
### ---Issue Report---
**Have you checked the Known Issues page (if applicable & PLEASE CHECK BEFORE POSTING):No [Yes or No]

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):No [Yes or No]
### Description of Issue
I can launch this mod pack,even reinstall and restart many time still can't launch it.buy else mod pack can lauch with FTp launcher.

### Steps to Reproduce Issue
1. [First step]
2. [Second step]

**Crash log/Log (if applicable):[FTBLauncherLog.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/851368/FTBLauncherLog.txt)
[MinecraftLog.txt](https://github.com/MJRLegends/Space-Astronomy-Feedback-/files/851367/MinecraftLog.txt) [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]

**Version of Mod Pack using:1.6.0 [VERSION]

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by MJRLegends** [comment]
Reinstall or use a different launcher

Your error is with forge not my mod pack
```
[01:19:50] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.NullPointerException
	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:137) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-17.0.jar:?]
	at com.google.common.hash.AbstractByteHasher.putBytes(AbstractByteHasher.java:69) ~[guava-17.0.jar:?]
	at com.google.common.hash.AbstractStreamingHashFunction.hashBytes(AbstractStreamingHashFunction.java:57) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:97) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:61) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:193) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:170) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:139) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at cpw.mods.fml.common.asm.FMLSanityChecker.injectData(FMLSanityC
```

**Comment by jeremywu0521** [comment]
Still can't launcher,I reinstall launcher but can't launch

**Comment by fid3n** [comment]
how u fixed?
