### ISSUE TITLE
****KNOWN ISSUES THREAD****

### ISSUE THREAD

**Issue by MJRLegends** [MJRLegends/Space-Astronomy-Feedback-#934]
## Known Issues: 
1. HQM Crashing world - If your world wont load and gets stuck when loading the dimensions, after updating. OR Getting this crash "java.lang.ArrayIndexOutOfBoundsException: at hardcorequesting.network.DataReader.readData(DataReader.java:55)"(http://pastebin.com/VDNpxfBy) or this crash "java.lang.NullPointerException: Exception in server tick loop
at hardcorequesting.QuestingData.(QuestingData.java:524)"
 **********This is a HQM Mod bug not a mod pack bug!**********
**Solution 1:** Delete this folder "C:\Users\USERNAME\AppData\Roaming\ftblauncher\SpaceAstronomy\minecraft\Saves\YOURSAVE\HardcoreQuesting" replace "USERNAME" with your computer username and then replace "YOURSAVE" with your world folder name. (You will lose all your quest progress!!!) But you can use "/hqm edit" command to complete the quests you did before!!!
**Solution 2:** Start a new world.
----------------------------------------------------------------
2. Error when loading mod pack on curse - "java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable" crash. This crash is a problem with the curse lanucher, and is to do with the installing of forge and i am in the process of fixing this with the FTB Team. This is not a pack related bug!!!
**Solution 1:** Use these settings in curse https://gyazo.com/0c8fa678c9a601f0b8276e37f06afab4
**Solution 2:** Use the FTB Launcher.
**Solution 3:** Disable/delete the Open Computers mod
**Solution 4:** Try this - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293018-opencomputers-v1-5-16?comment=1298
----------------------------------------------------------------
3. Wither skulls dupe - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/119 - (This is a mod bug) Reported in v1.3.0!
-----------------------------------------------------------------
4. Soul aspect drops from cows - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/255 - (This is a mod bug) Reported in v1.4.1!
-----------------------------------------------------------------
5. Crash when using KCauldron/Thermos to run a server - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/275 - (This is a kcauldron bug so people wont really get this is there not running a proper server and just using forge)
**Solution 1:** Try changing the option "load chunk on request" to false in cauldron.yml
-----------------------------------------------------------------
6. Immersive engineering TileEntityImmersiveConnectable Crash - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/341 - (This is a mod bug)
**Solution 1:** Remove ImmersiveEngineering and then load the world and then add it back (will remove everything in your world related to the mod)
**Solution 2:** Edit the blocks out (coords can be found in the crash log above the mod list) using MCEdit
-----------------------------------------------------------------
7. Advanced Genetics TileEntityDNACombiner Crash - http://pastebin.com/FPGG8Bxc - (This is a mod bug)
**Solution 1:** Remove Advanced Genetics and then load the world and then add it back (will remove everything in your world related to the mod)
**Solution 2:** Edit the blocks out (coords can be found in the crash log above the mod list) using MCEdit
-----------------------------------------------------------------
8. Crash when putting in quest book into autonomous activator - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/398 - (This is a mod bug)
-----------------------------------------------------------------
9. Dupe with Project Red Transportation - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/431 - (This is a mod bug)
-----------------------------------------------------------------
10. Haste on Traveller's Gloves not working - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/453
-----------------------------------------------------------------
11. Dark Steel Armor Glitch - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/518
-----------------------------------------------------------------
12. Extra Utilities Soul fragment crafting bug/glitch (When 30% is removed not 10%)- https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/566 - (This is a mod bug)
**Solution 1:** Spawn the creative soul fragment from nei and right click which will give you +10% per item (Keep repeating when needed)
**Solution 2:** Edit player data file (Tutorial https://www.youtube.com/watch?v=5Ue8gqo7EP0)
-----------------------------------------------------------------
13. Minecraft crashes after moving opencomputer with matter transpoter - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/680
-----------------------------------------------------------------
14. Ender Pearl Powder from Ender IO doesn't show up in NEI - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/697
-----------------------------------------------------------------
15. Crash when using a Flux-Infused OmniWench on a Energy-O-Mat - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/765
-----------------------------------------------------------------
16. Duplicating compressed redstone / carbon - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/493 & https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/656 - Fixed If and When the developer releases the build containing the fix
-----------------------------------------------------------------
17. Bounding Box issue with MFR Conveyor belt - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/903
**Solution 1:** Conveyor belt added by Immersive Engineering and Extra Utils shouldn't have the same issue

**Comment by cheesyman101** [comment]
Buildcraft quarry is crashing my game when I load my world. Quarry is in the mining dimension and I can't fix it.
